name: dc_community_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

  cupertino_icons: ^0.1.2
  universal_html: ^1.1.20
  url_launcher: ^5.4.2
  http: ^0.12.0+4
  marquee: ^0.0.2
  device_preview: ^0.4.8

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/